In [1]:
import pandas as pd
import numpy as np

### reshape and transpose


In [2]:
# 4차원 배열 생성 (2, 3, 4, 5)
arr = np.arange(2 * 3 * 4 * 5).reshape(2, 3, 4, 5)
# Transpose 축 순서 변경
transposed_arr = arr.transpose(0, 2, 3, 1)

In [10]:
arr[1]

array([[[ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74],
        [ 75,  76,  77,  78,  79]],

       [[ 80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94],
        [ 95,  96,  97,  98,  99]],

       [[100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119]]])

In [8]:
transposed_arr[1]

array([[[ 60,  80, 100],
        [ 61,  81, 101],
        [ 62,  82, 102],
        [ 63,  83, 103],
        [ 64,  84, 104]],

       [[ 65,  85, 105],
        [ 66,  86, 106],
        [ 67,  87, 107],
        [ 68,  88, 108],
        [ 69,  89, 109]],

       [[ 70,  90, 110],
        [ 71,  91, 111],
        [ 72,  92, 112],
        [ 73,  93, 113],
        [ 74,  94, 114]],

       [[ 75,  95, 115],
        [ 76,  96, 116],
        [ 77,  97, 117],
        [ 78,  98, 118],
        [ 79,  99, 119]]])

### dot and element-wise operation


In [18]:
A = np.arange(2*2).reshape(2,2)
B = np.array([[3,4],
              [5,6]])

print(f'Mat A:{A}')
print(f'Mat A:{B}')
print("===========")

# dot product AB
print("Dot Product")
print(A @ B)
print(np.dot(A,B))
print("===========")

print("Element-wise operation")
print(A * B)
print(np.multiply(A,B))
print("===========")


Mat A:[[0 1]
 [2 3]]
Mat A:[[3 4]
 [5 6]]
Dot Product
[[ 5  6]
 [21 26]]
[[ 5  6]
 [21 26]]
Element-wise operation
[[ 0  4]
 [10 18]]
[[ 0  4]
 [10 18]]


In [19]:
data = pd.read_csv('shorts_db.csv')

In [28]:
data.groupby(['channel_name','check_date']).count()

shorts_url  \
channel_name                                check_date               
#춤추는곰돌 #랜덤댄스 #춤추는곰돌의랜덤댄스 #afstarz           False                0   
(G)I-DLE (여자)아이들 (Official YouTube Channel) 2024-11-24           1   
                                            2024-11-26           2   
                                            2024-11-27           1   
(주)율아트 방송특수소품                               2024-11-24           1   
...                                                            ...   
💖Darisha💖                                   2024-11-26           2   
                                            2024-11-27           1   
💜BTS ARMY💜                                  2024-11-24           1   
                                            2024-11-26           2   
                                            2024-11-27           1   

                                                        shorts_title  \
channel_name                                check_date                 
#춤추는곰돌 #랜덤댄스 #춤추는곰돌의랜덤댄스 #afstarz           False                  1   
(G)I-DLE (여자)아이들 (Official YouTube Channel) 2024-11-24             1   
                                            2024-11-26             0   
                                            2024-11-27             1   
(주)율아트 방송특수소품                               2024-11-24             0   
...                                                              ...   
💖Darisha💖                                   2024-11-26             2   
                                            2024-11-27             0   
💜BTS ARMY💜                                  2024-11-24             0   
                                            2024-11-26             2   
                                            2024-11-27             0   

                                                        shorts_description  \
channel_name                                check_date                       
#춤추는곰돌 #랜덤댄스 #춤추는곰돌의랜덤댄스 #afstarz           False                        1   
(G)I-DLE (여자)아이들 (Official YouTube Channel) 2024-11-24                   0   
                                            2024-11-26                   1   
                                            2024-11-27                   0   
(주)율아트 방송특수소품                               2024-11-24                   0   
...                                                                    ...   
💖Darisha💖                                   2024-11-26                   1   
                                            2024-11-27                   0   
💜BTS ARMY💜                                  2024-11-24                   0   
                                            2024-11-26                   2   
                                            2024-11-27                   1   

                                                        shorts_thumbnail  \
channel_name                                check_date                     
#춤추는곰돌 #랜덤댄스 #춤추는곰돌의랜덤댄스 #afstarz           False                      1   
(G)I-DLE (여자)아이들 (Official YouTube Channel) 2024-11-24                 0   
                                            2024-11-26                 0   
                                            2024-11-27                 0   
(주)율아트 방송특수소품                               2024-11-24                 0   
...                                                                  ...   
💖Darisha💖                                   2024-11-26                 1   
                                            2024-11-27                 0   
💜BTS ARMY💜                                  2024-11-24                 0   
                                            2024-11-26                 1   
                                            2024-11-27                 0   

                                                        shorts_view  \
channel_name                                check_date                
#춤추는곰돌 #랜덤댄스 #춤추는곰돌의랜덤댄스 #afstarz           False             