In [45]:
import tensorflow as tf
random_seed = 0

# 12.2 Use Tensorflow like Numpy

tf.constant(): create immutable constant tensor


In [53]:
t = tf.constant([[1., 2., 3.], [4., 5., 6.]])

print("1. Constant Tensor")
print(t) # Show variable
print('')

print(f't.shape: {t.shape}')
print(f't.dtype: {t.dtype}')
print(f't[:, 1:] \n {t[:, 1:]}')

1. Constant Tensor
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)

t.shape: (2, 3)
t.dtype: <dtype: 'float32'>
t[:, 1:] 
 [[2. 3.]
 [5. 6.]]


In [54]:
t

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

### 12.2.1 Operation


In [55]:
# Matrix Multiplication
tf.square(t) 
t @ tf.transpose(t)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

In [56]:
# Elementwise multiplication
t * t

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

#### tf.squeeze

- 크기가 1인 차원(Axis)을 제거


In [57]:
x = tf.constant([[[1], [2], [3]]])  # Shape: (1, 3, 1)
print(x)  # Output: [[[1], [2], [3]]]
print(f"shape before squeeze {x.shape}")
result = tf.squeeze(x)  # Shape: (3,)
print(f"shape after squeeze {result.shape}")
print(result)  # Output: [1, 2, 3]


tf.Tensor(
[[[1]
  [2]
  [3]]], shape=(1, 3, 1), dtype=int32)
shape before squeeze (1, 3, 1)
shape after squeeze (3,)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)


### tf.tile(input, multiples)

- 특정 차원(axis)을 따라 복제(반복)합니다

Parameters

- input: 복제할 대상 텐서.
- multiples: 각 축(axis)에서 반복할 횟수를 나타내는 정수 리스트.


In [58]:
x = tf.constant([[1, 2],
                 [3, 4]])  # Shape: (2, 2)

# Repeat 2 times along axis 0, 3 times along axis 1
result = tf.tile(x, multiples=[2, 3])  # Shape: (4, 6)
print(result)


tf.Tensor(
[[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]], shape=(4, 6), dtype=int32)


### 12.2.3 Type Casting

- tensorflow does not automatically cast any data types
- any operation between other data type will raise error


In [59]:
t2 = tf.constant(40., dtype = tf.float64)
t2 = tf.cast(t2, tf.float32)

### 12.2.4 Variable

- tf.constant is immutable
- for weight update, need variable to work with


In [64]:
v = tf.Variable([[1., 2., 3.,], [4., 5., 6.]])
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

#### assign

- tf variable valus cannot be normally changed
- need assign function to change variable values


In [71]:
v.assign(2 * v) #[2., 4., 6.]
v[0, 1].assign(42) # (0,1) element become 42
v[:, 2].assign([0.1, 1.0]) # all rows at 2nd column become 0.1, 1.0

# Assign new values for speicif elements
v.scatter_nd_update(
    indices = [[0,0], [1,2]], updates = [100., 200.]
)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[1.00e+02, 4.20e+01, 1.00e-01],
       [5.12e+02, 6.40e+02, 2.00e+02]], dtype=float32)>

### Data Types

**1. `tf.SparseTensor`**

- **설명**: 희소 텐서를 표현. 대부분의 값이 0인 데이터를 효율적으로 저장.
- **사용 예**: 희소 행렬(예: 원-핫 인코딩, NLP에서 단어 벡터).
- **특징**:
  - 좌표(`indices`), 값(`values`), 전체 모양(`dense_shape`)으로 구성.
  - 메모리 사용량을 줄임.

**2. `tf.TensorArray`**

- **설명**: 가변 길이의 텐서 배열. 반복문이나 그래프 모드에서 동적으로 텐서를 저장/추출.
- **사용 예**: RNN, 동적 계산 그래프에서 중간 계산 결과 저장.
- **특징**:
  - 정적 크기 및 동적 크기 지원.
  - GPU 및 TPU와 호환 가능.

**3. `tf.RaggedTensor`**

- **설명**: 불규칙한 길이를 가진 데이터를 표현하는 텐서.
- **사용 예**: NLP(문장 길이가 다른 배치), 시퀀스 데이터.
- **특징**:
  - 행마다 길이가 다를 수 있음.
  - 예: `[[1, 2], [3], [4, 5, 6]]` (모양: `[3, None]`).

**4. `tf.string`**

- **설명**: 문자열 데이터를 다루는 텐서.
- **사용 예**: 텍스트 데이터 처리, 파일 경로 관리.
- **특징**:
  - 텐서 내부에 문자열 저장 가능.
  - 문자열은 이진 데이터도 포함 가능.

**5. `tf.sets`**

- **설명**: 집합 연산을 위한 API 제공(예: 교집합, 합집합, 차집합).
- **사용 예**: NLP에서 단어 집합 처리, 고유 데이터 계산.
- **특징**:
  - `SparseTensor` 기반으로 동작.
  - `tf.sets.intersection`, `tf.sets.union` 등의 함수 제공.

**6. `tf.queue`**

- **설명**: 입력 데이터의 대기열(queue)을 처리. (TensorFlow 1.x에서 주로 사용됨.)
- **사용 예**: 데이터 입력 파이프라인(큐에서 데이터 읽기/쓰기).
- **특징**:
  - FIFOQueue, RandomShuffleQueue 등의 구현 제공.
  - **TensorFlow 2.x에서는 `tf.data` API**로 대체됨.


# 12.3 Customized Model and Training Algorithm


### 12.3.1 Customized Loss Function

- **MSE** gives too much penalty for a large error, so it's very sensitive to noises or outliers
- **MAE** gives too less penalty for a large error, so the training won't be good enough or too slow to train
- **Huber** might be useful for this case
- Many loss functions are already included in the keras, but pretend it doesn exists


In [ ]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow import keras

housing = fetch_california_housing()
X_train_full, X_test, y_train_full, y_test = train_test_split(
    housing.data, housing.target.reshape(-1, 1), random_state=42)
X_train, X_valid, y_train, y_valid = train_test_split(
    X_train_full, y_train_full, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_valid_scaled = scaler.transform(X_valid)
X_test_scaled = scaler.transform(X_test)

input_shape = X_train_scaled.shape[1:]

tf.random.set_seed(42)
model = tf.keras.Sequential([
    tf.keras.layers.Input(input_shape),
    tf.keras.layers.Dense(30, activation="relu", kernel_initializer="he_normal"),
    tf.keras.layers.Dense(1),
])

class HuberLoss(tf.keras.losses.Loss):
    def __init__(self, threshold=1.0, **kwargs):
        self.threshold = threshold
        super().__init__(**kwargs)

    def call(self, y_true, y_pred):
        error = y_true - y_pred
        is_small_error = tf.abs(error) < self.threshold
        squared_loss = tf.square(error) / 2
        linear_loss  = self.threshold * tf.abs(error) - self.threshold**2 / 2
        return tf.where(is_small_error, squared_loss, linear_loss)

    def get_config(self):
        base_config = super().get_config()
        return {**base_config, "threshold": self.threshold}
    

model.compile(loss=HuberLoss(2.), optimizer="nadam", metrics=["mae"])

model.fit(X_train_scaled, y_train, epochs=2,
          validation_data=(X_valid_scaled, y_valid))


# Save the model with customized loss
model.save("./120/custom_loss_model.keras")

# Load the model with customized loss
loaded_model = tf.keras.models.load_model("./120/custom_loss_model.keras",
                                   custom_objects={"HuberLoss": HuberLoss})

loaded_model.compile(loss = HuberLoss(3.0), optimizer = 'adam')
#  정상적으로 로드되고 모델을 정상적으로 사용할 수 있음을 보여줍니다.
loaded_model.fit(X_train_scaled, y_train, epochs=2,
          validation_data=(X_valid_scaled, y_valid))

Epoch 1/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 462us/step - loss: 2.5190 - mae: 2.0277 - val_loss: 0.4348 - val_mae: 0.6962
Epoch 2/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 320us/step - loss: 0.3911 - mae: 0.6600 - val_loss: 0.2791 - val_mae: 0.5451
Epoch 1/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 436us/step - loss: 0.2888 - mae: 0.5493 - val_loss: 0.2514 - val_mae: 0.4894
Epoch 2/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 303us/step - loss: 0.2400 - mae: 0.5004 - val_loss: 0.2085 - val_mae: 0.4625


### 12.3.3 Customizing activation function, initializer, regulation, and limitation


In [ ]:
housing = fetch_california_housing()
X_train_full, X_test, y_train_full, y_test = train_test_split(
    housing.data, housing.target.reshape(-1, 1), random_state=42)
X_train, X_valid, y_train, y_valid = train_test_split(
    X_train_full, y_train_full, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_valid_scaled = scaler.transform(X_valid)
X_test_scaled = scaler.transform(X_test)

input_shape = X_train_scaled.shape[1:]


# Define the customized functions
def my_softplus(z):
    return tf.math.log(1.0 + tf.exp(z))

def my_glorot_initializer(shape, dtype=tf.float32):
    stddev = tf.sqrt(2. / (shape[0] + shape[1]))
    return tf.random.normal(shape, stddev=stddev, dtype=dtype)

def my_l1_regularizer(weights):
    return tf.reduce_sum(tf.abs(0.01 * weights))

def my_positive_weights(weights):  # 반환 값은 tf.nn.relu(weights)입니다.
    return tf.where(weights < 0., tf.zeros_like(weights), weights)

@keras.utils.register_keras_serializable()
class MyL1Regularizer(tf.keras.regularizers.Regularizer):
    def __init__(self, factor):
        self.factor = factor

    def __call__(self, weights):
        return tf.reduce_sum(tf.abs(self.factor * weights))

    def get_config(self):
        return {"factor": self.factor}
    

input_shape = X_train_scaled.shape[1:]
    
# train with the customized model
tf.random.set_seed(42)
model = tf.keras.Sequential([
    tf.keras.layers.Input(input_shape),
    tf.keras.layers.Dense(30, activation="relu", kernel_initializer="he_normal"),
    tf.keras.layers.Dense(1, activation=my_softplus,
                          kernel_initializer=my_glorot_initializer,
                          kernel_regularizer=MyL1Regularizer(0.01))
])

model.compile(loss="mse", optimizer="nadam", metrics=["mae"])

model.fit(X_train_scaled, y_train, epochs=2,
          validation_data=(X_valid_scaled, y_valid))

model.save("./120/my_model_with_many_custom_parts.keras")

loaded_model = tf.keras.models.load_model(
    "./120/my_model_with_many_custom_parts.keras",
    custom_objects={
       "my_l1_regularizer": MyL1Regularizer,
       "my_glorot_initializer": my_glorot_initializer,
       "my_softplus": my_softplus,
    }
)

loaded_model.fit(X_train_scaled, y_train, epochs=2,
          validation_data=(X_valid_scaled, y_valid))


loaded_model.layers[-1].kernel_regularizer.get_config()

Epoch 1/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 467us/step - loss: 3.0827 - mae: 1.2805 - val_loss: 0.7606 - val_mae: 0.6066
Epoch 2/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 324us/step - loss: 0.7635 - mae: 0.6057 - val_loss: 0.5594 - val_mae: 0.5060
Epoch 1/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 475us/step - loss: 0.5965 - mae: 0.5237 - val_loss: 0.4857 - val_mae: 0.4651
Epoch 2/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 330us/step - loss: 0.5292 - mae: 0.4865 - val_loss: 0.4530 - val_mae: 0.4453


{'factor': 0.01}

### 12.3.4 Customized metrics

- loss and metric are similar but different
- loss is used for training, differentiable and gradient is not for all domain
- metric have no condition but it need to be easy to interpret


In [116]:
model = tf.keras.Sequential([
    tf.keras.layers.Input(input_shape),
    tf.keras.layers.Dense(30, activation="relu", kernel_initializer="he_normal",),
    tf.keras.layers.Dense(1),
])

model.compile(loss = 'mse', optimizer='nadam', metrics = [HuberLoss(2.0)])

model.fit(X_train_scaled, y_train, epochs=2)

Epoch 1/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 262us/step - huber_loss_5: 1.2148 - loss: 2.8134
Epoch 2/2
363/363 ━━━━━━━━━━━━━━━━━━━━ 0s 239us/step - huber_loss_5: 0.3255 - loss: 0.6772
